### ISSUE TITLE
Manually bind `IBV_SEND_INLINE` etc. for work request flags.

### ISSUE THREAD

**Issue by dragonJACson** [RDMA-Rust/rdma-mummy-sys#9]

**Comment by FujiZ** [comment]
Those flags are already available in the binding
![图片](https://github.com/user-attachments/assets/3b61344b-0d8c-46f8-a8bb-d2f94510862f)

**Comment by dragonJACson** [comment]
> Those flags are already available in the binding ![图片](https://private-user-images.githubusercontent.com/11678436/366473530-3b61344b-0d8c-46f8-a8bb-d2f94510862f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNjE1NzksIm5iZiI6MTcyNjA2MTI3OSwicGF0aCI6Ii8xMTY3ODQzNi8zNjY0NzM1MzAtM2I2MTM0NGItMGQ4Yy00NmY4LWE4YmItZDJmOTQ1MTA4NjJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDEzMjc1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzOWNlMjU3MTExYWZjZjkzYjk2Yzc4ZjFhNjQzZjliOWFkMjEzM2JiNjdkNDJhMWZiNmZkZjdhMzI5ODc0YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f62VnwswBm5cZybA7f5k8BGf0loOZz9I49EQK3NSKHo)

Ooops, thanks, just missed it :-(
